# 这个是配置文件的版本，不同的版本号声明方式会有细微的不同
version: '3.7'
services:
  docker_compose_blog_client:
    # docker构建镜像
    build:
      context: .
      dockerfile: Dockerfile
    # docker启动的服务名
    container_name: docker_container_blog_client
    # 启动服务依赖的镜像名
    image: docker_image_blog_client
    # 启动服务时将服务的7001端口对外映射到7001端口
    # 后面的是docker端口，前面的是映射到本机的端口
    ports:
      - '80:4000'
    # 映射上传文件的目录
    volumes:
      - /root/blog-upload/upload:/blog-client/public/upload
    # 重启
    restart: always
    # 设置网络模式, 同docker run --net=docker_network_blog
    # 就是指定加入已存在的network
    network_mode: 'docker_network_blog'
